// packages/audio-components/src/frameworks/react/primitives/knob/KnobComponent.tsx
// src/frameworks/react/primitives/knob/KnobComponent.tsx
/** @jsx React.createElement */
/** @jsxRuntime classic */
import React, { useEffect, useRef, useState, useCallback } from 'react';

import {
  KnobElement,
  KnobConfig,
  KnobChangeEventDetail,
  createKnobElement,
} from '../../../../elements/primitives/KnobElement';

import {
  KnobPresetProps,
  KnobPresetKey,
} from '../../../solidjs/primitives/knob/KnobPresets';

export interface KnobComponentProps extends Partial<KnobConfig> {
  preset?: KnobPresetKey;
  size?: number;
  color?: string;
  value?: number;
  onChange?: (detail: KnobChangeEventDetail) => void;
  ref?: React.Ref<KnobElement>;

  // Value display props
  displayValue?: boolean;
  valueFormatter?: (value: number) => string;

  // Snap configuration
  snapThresholds?: Array<{ maxValue: number; increment: number }>;
  allowedValues?: number[];

  // Tooltip support
  title?: string;

  // Style props
  label?: string;
  className?: string; // Applied to root container
  labelClassName?: string; // Applied to label
  knobClassName?: string; // Applied to knob element
  valueClassName?: string; // Applied to value display
  style?: React.CSSProperties | string;
  labelStyle?: React.CSSProperties;
  valueStyle?: React.CSSProperties;
}

export const KnobComponent = React.forwardRef<KnobElement, KnobComponentProps>(
  (props, ref): React.ReactElement => {
    const containerRef = useRef<HTMLDivElement>(null);
    const knobInstanceRef = useRef<KnobElement | null>(null);
    const [currentValue, setCurrentValue] = useState(
      () => props.value ?? props.defaultValue ?? 0
    );

    // Merge defaults, preset config, and props (props override preset and defaults)
    const merged = React.useMemo(
      () => ({
        displayValue: true,
        size: 45,
        ...(props.preset ? KnobPresetProps[props.preset] : {}),
        ...props,
      }),
      [props]
    );

    // Create knob instance once on mount
    useEffect(() => {
      if (!containerRef.current) return;

      // Create stable config object
      const config = {
        displayValue: true,
        size: 45,
        ...(props.preset ? KnobPresetProps[props.preset] : {}),
        ...props,
      };

      const knobOptions = {
        ...config,
        width: config.size, // Factory expects 'width'
        snapThresholds: config.snapThresholds,
        allowedValues: config.allowedValues,
      };

      const knobInstance = createKnobElement(containerRef.current, knobOptions);
      knobInstanceRef.current = knobInstance;

      // Apply knobClassName if provided
      if (props.knobClassName) {
        knobInstance.classList.add(...props.knobClassName.split(' '));
      }

      // Create event handler inside useEffect to avoid stale closures
      const handleChange = (e: CustomEvent<KnobChangeEventDetail>) => {
        setCurrentValue(e.detail.value);
        props.onChange?.(e.detail);
      };

      knobInstance.addEventListener(
        'knob-change',
        handleChange as EventListener
      );

      // Handle ref forwarding
      if (typeof ref === 'function') {
        ref(knobInstance);
      } else if (ref) {
        (ref as React.MutableRefObject<KnobElement>).current = knobInstance;
      }

      // Set initial value
      const initialValue = merged.value ?? merged.defaultValue ?? 0;
      setCurrentValue(initialValue);
      knobInstance.setValue(initialValue);

      return () => {
        knobInstance.removeEventListener(
          'knob-change',
          handleChange as EventListener
        );

        // Clean up the DOM by removing all children from the container
        if (containerRef.current) {
          containerRef.current.innerHTML = '';
        }

        knobInstanceRef.current = null;
      };
    }, []); // Empty dependency array - create only once

    // Update value when props.value changes (controlled component)
    useEffect(() => {
      if (
        knobInstanceRef.current &&
        props.value !== undefined &&
        props.value !== currentValue
      ) {
        knobInstanceRef.current.setValue(props.value);
        setCurrentValue(props.value);
      }
    }, [props.value, currentValue]);

    // Default label styles
    const defaultLabelStyle: React.CSSProperties = {
      textAlign: 'center',
      marginBottom: '4px',
    };

    // Merge default label styles with user-provided labelStyle
    const combinedLabelStyle: React.CSSProperties = {
      ...defaultLabelStyle,
      ...(merged.labelStyle && typeof merged.labelStyle === 'object'
        ? merged.labelStyle
        : {}),
    };

    // Default value styles
    const defaultValueStyle: React.CSSProperties = {
      fontSize: '10px',
      textAlign: 'center',
      color: '#999',
      marginTop: '4px',
    };

    // Merge default value styles with user-provided valueStyle
    const combinedValueStyle: React.CSSProperties = {
      ...defaultValueStyle,
      ...(merged.valueStyle && typeof merged.valueStyle === 'object'
        ? merged.valueStyle
        : {}),
    };

    // Default formatter if none provided
    const formatter = merged.valueFormatter || ((v: number) => v.toFixed(2));

    // Simple render without label or value display
    if (!merged.label && !merged.displayValue) {
      return React.createElement('div', {
        ref: containerRef,
        title: merged.title,
      });
    }

    // Full render with label and/or value display
    return React.createElement(
      'div',
      {
        className: merged.className || 'knob-container',
        style: typeof merged.style === 'string' ? undefined : merged.style,
        title: merged.title,
      },
      [
        merged.label &&
          React.createElement(
            'div',
            {
              key: 'label',
              className: merged.labelClassName || 'knob-label',
              style: combinedLabelStyle,
            },
            merged.label
          ),
        React.createElement('div', {
          key: 'knob',
          ref: containerRef,
        }),
        merged.displayValue &&
          React.createElement(
            'div',
            {
              key: 'value',
              className: merged.valueClassName || 'knob-value',
              style: combinedValueStyle,
            },
            formatter(currentValue)
          ),
      ].filter(Boolean)
    );
  }
);

KnobComponent.displayName = 'KnobComponent';

export default KnobComponent;

// packages/audio-components/src/frameworks/solidjs/primitives/knob/KnobComponent.tsx
// src/frameworks/solidjs/KnobComponent.tsx
import {
  Component,
  createEffect,
  onMount,
  onCleanup,
  mergeProps,
  Show,
  createSignal,
} from 'solid-js';

import {
  KnobElement,
  KnobConfig,
  KnobChangeEventDetail,
  createKnobElement,
} from '../../../../elements/primitives/KnobElement';

import { KnobPresetProps, KnobPresetKey } from './KnobPresets';

export interface KnobComponentProps extends Partial<KnobConfig> {
  preset?: KnobPresetKey;
  size?: number;
  color?: string;
  value?: number;
  onChange?: (detail: KnobChangeEventDetail) => void;
  ref?: (el: KnobElement) => void;

  // Value display props
  displayValue?: boolean;
  valueFormatter?: (value: number) => string;

  // Snap configuration
  snapThresholds?: Array<{ maxValue: number; increment: number }>;
  allowedValues?: number[];

  // Tooltip support
  title?: string;

  // Style props
  label?: string;
  class?: string; // Applied to root container
  labelClass?: string; // Applied to label
  knobClass?: string; // Applied to knob element
  valueClass?: string; // Applied to value display
  style?: string | Record<string, string>;
  labelStyle?: string | Record<string, string>;
  valueStyle?: string | Record<string, string>;
}

export const KnobComponent: Component<KnobComponentProps> = (props) => {
  let containerRef: HTMLDivElement | undefined;
  let knobInstance: KnobElement | undefined;

  // Track current value for display
  const [currentValue, setCurrentValue] = createSignal(0);

  // Merge defaults, preset config, and props (props override preset and defaults)
  const merged = mergeProps(
    { displayValue: true, size: 45 }, // Default values
    props.preset ? KnobPresetProps[props.preset] : {},
    props
  );

  onMount(() => {
    if (!containerRef) return;

    // Pass merged config to factory, converting size to width
    const knobOptions = {
      ...merged,
      width: merged.size, // Factory expects 'width'
      snapThresholds: merged.snapThresholds,
      allowedValues: merged.allowedValues,
    };

    knobInstance = createKnobElement(containerRef, knobOptions);

    // Apply knobClass if provided
    if (props.knobClass) {
      knobInstance.classList.add(...props.knobClass.split(' '));
    }

    const handleChange = (e: CustomEvent<KnobChangeEventDetail>) => {
      setCurrentValue(e.detail.value);
      props.onChange?.(e.detail);
    };

    knobInstance.addEventListener('knob-change', handleChange as EventListener);
    props.ref?.(knobInstance);

    // Set initial value for display
    setCurrentValue(merged.value ?? merged.defaultValue ?? 0);

    onCleanup(() => {
      knobInstance?.removeEventListener(
        'knob-change',
        handleChange as EventListener
      );
    });
  });

  createEffect(() => {
    if (knobInstance && merged.value !== undefined) {
      knobInstance.setValue(merged.value);
    }
  });

  // Default label styles
  const defaultLabelStyle = {
    'text-align': 'center',
    'margin-bottom': '4px',
  };

  // Merge default label styles with user-provided labelStyle
  const combinedLabelStyle = {
    ...defaultLabelStyle,
    ...(typeof merged.labelStyle === 'string' ? {} : merged.labelStyle || {}),
  };

  // Convert to string if needed
  const labelStyleString =
    typeof merged.labelStyle === 'string'
      ? `text-align: center; margin-bottom: 4px; ${merged.labelStyle}`
      : Object.entries(combinedLabelStyle)
          .map(([key, value]) => `${key}: ${value}`)
          .join('; ');

  // Default value styles
  const defaultValueStyle = {
    'font-size': '10px',
    'text-align': 'center',
    color: '#999',
    'margin-top': '4px',
  };

  // Merge default value styles with user-provided valueStyle
  const combinedValueStyle = {
    ...defaultValueStyle,
    ...(typeof merged.valueStyle === 'string' ? {} : merged.valueStyle || {}),
  };

  // Convert to string if needed
  const valueStyleString =
    typeof merged.valueStyle === 'string'
      ? `font-size: 10px; text-align: center; color: #999; ${merged.valueStyle}`
      : Object.entries(combinedValueStyle)
          .map(([key, value]) => `${key}: ${value}`)
          .join('; ');

  // Default formatter if none provided
  const formatter = merged.valueFormatter || ((v: number) => v.toFixed(2));

  return (
    <Show
      when={merged.label || merged.displayValue}
      fallback={<div ref={containerRef!} title={merged.title} />}
    >
      <div
        class={merged.class || 'knob-container'}
        style={merged.style}
        title={merged.title}
      >
        <Show when={merged.label}>
          <div
            class={merged.labelClass || 'knob-label'}
            style={labelStyleString}
          >
            {merged.label}
          </div>
        </Show>
        <div ref={containerRef!} />
        <Show when={merged.displayValue}>
          <div
            class={merged.valueClass || 'knob-value'}
            style={valueStyleString}
          >
            {formatter(currentValue())}
          </div>
        </Show>
      </div>
    </Show>
  );
};

export default KnobComponent;

// export interface KnobComponentProps extends Partial<KnobConfig> {
//   preset?: KnobPresetKey;

//   // Visual props
//   width?: number;
//   knobColor?: string;
//   labelColor?: string;

//   // Value props
//   value?: number;

//   // Label
//   label?: string;
//   labelClass?: string;

//   // Event handlers
//   onChange?: (detail: KnobChangeEventDetail) => void;

//   // Standard HTML props
//   class?: string;
//   style?: string | Record<string, string>;
//   ref?: (el: KnobElement) => void;
// }

// const DEFAULT_KNOB_PROPS: Partial<KnobConfig> = {
//   minValue: 0,
//   maxValue: 1,
//   defaultValue: 0,
//   snapIncrement: 0.001,
//   minRotation: -150,
//   maxRotation: 150,
//   curve: 1,
//   disabled: false,
//   borderStyle: 'currentState' as const,
// };

// /**
//  * SolidJS wrapper component for KnobElement web component
//  */
// export const KnobComponent: Component<KnobComponentProps> = (props) => {
//   let containerRef: HTMLDivElement | undefined;
//   let knobInstance: KnobElement;

//   // Set up default props
//   const presetConfig = props.preset ? KnobPresetProps[props.preset] : {};
//   const merged = mergeProps(DEFAULT_KNOB_PROPS, presetConfig, props);

//   // Calculate the effective knob size for label styling
//   const getKnobSize = () => {
//     // Default knob size from CSS custom property or fallback
//     const defaultSize = 120;
//     return merged.width || defaultSize;
//   };

//   // Generate label styles that scale with knob size
//   const getLabelStyle = () => {
//     const knobSize = getKnobSize();
//     // Scale font size proportionally to knob size (adjust multiplier as needed)
//     const fontSize = Math.max(10, knobSize * 0.2); // Min 10px, ~20% of knob size
//     const color = merged.labelColor || 'inherit';

//     return {
//       'font-size': `${fontSize}px`,
//       color: color,
//       'text-align': 'center',
//       'white-space': 'nowrap',
//     };
//   };

//   // Support style as object as well as string
//   const getStyleString = (
//     style: string | Record<string, string> | undefined
//   ) => {
//     if (!style) return undefined;
//     if (typeof style === 'string') return style;
//     return Object.entries(style)
//       .map(([key, value]) => `${key}: ${value}`)
//       .join('; ');
//   };

//   onMount(() => {
//     if (!customElements.get('knob-element')) {
//       throw new Error('knob-element not registered. Import KnobElement first.');
//     }

//     knobInstance = document.createElement('knob-element') as KnobElement;
//     updateKnobAttributes();

//     const handleChange = (e: CustomEvent<KnobChangeEventDetail>) => {
//       merged.onChange?.(e.detail);
//     };
//     knobInstance.addEventListener('knob-change', handleChange as EventListener);

//     if (containerRef) {
//       containerRef.appendChild(knobInstance);
//     }

//     merged.ref?.(knobInstance);

//     if (merged.value !== undefined && merged.value !== merged.defaultValue) {
//       requestAnimationFrame(() => {
//         knobInstance.setValue(merged.value!);
//       });
//     }

//     onCleanup(() => {
//       knobInstance.removeEventListener(
//         'knob-change',
//         handleChange as EventListener
//       );
//       knobInstance.remove();
//     });
//   });

//   const updateVisualAttributes = () => {
//     if (!knobInstance) return;
//     try {
//       if (merged.width)
//         knobInstance.setAttribute('width', merged.width.toString());
//       if (merged.knobColor)
//         knobInstance.setAttribute('color', merged.knobColor);
//       if (merged.disabled) {
//         knobInstance.setAttribute('disabled', '');
//       } else {
//         knobInstance.removeAttribute('disabled');
//       }
//     } catch (error) {
//       console.warn('Failed to update visual attributes:', error);
//     }
//   };

//   const updateValueAttributes = () => {
//     if (!knobInstance) return;
//     try {
//       knobInstance.setAttribute('min-value', (merged.minValue ?? 0).toString());
//       knobInstance.setAttribute('max-value', (merged.maxValue ?? 1).toString());
//       knobInstance.setAttribute(
//         'default-value',
//         (merged.defaultValue ?? 0).toString()
//       );
//       knobInstance.setAttribute(
//         'snap-increment',
//         (merged.snapIncrement ?? 0.001).toString()
//       );
//       knobInstance.setAttribute(
//         'min-rotation',
//         (merged.minRotation ?? -150).toString()
//       );
//       knobInstance.setAttribute(
//         'max-rotation',
//         (merged.maxRotation ?? 150).toString()
//       );

//       if (merged.curve !== undefined) {
//         knobInstance.setAttribute('curve', merged.curve.toString());
//       }
//       if (merged.borderStyle) {
//         knobInstance.setAttribute('border-style', merged.borderStyle);
//       }
//       if (merged.allowedValues) {
//         knobInstance.setAttribute(
//           'allowed-values',
//           JSON.stringify(merged.allowedValues)
//         );
//       }
//       if (merged.snapThresholds) {
//         knobInstance.setAttribute(
//           'snap-thresholds',
//           JSON.stringify(merged.snapThresholds)
//         );
//       }
//     } catch (error) {
//       console.warn('Failed to update value attributes:', error);
//     }
//   };

//   const updateKnobAttributes = () => {
//     updateVisualAttributes();
//     updateValueAttributes();
//   };

//   createEffect(() => {
//     if (!knobInstance) return;
//     updateVisualAttributes();
//   });

//   createEffect(() => {
//     if (!knobInstance) return;
//     updateValueAttributes();
//   });

//   createEffect(() => {
//     if (!knobInstance || merged.value === undefined) return;
//     knobInstance.setValue(merged.value);
//   });

//   // Note: Label styles are automatically reactive through getLabelStyle()
//   // which reads merged.width and merged.labelColor

//   return (
//     <div
//       class={merged.class}
//       style={
//         typeof merged.style === 'string'
//           ? `${getStyleString({ display: 'block', gap: '8px' })}; ${merged.style}`
//           : getStyleString({
//               display: 'block',
//               gap: '8px',
//               ...(merged.style ?? {}),
//             })
//       }
//     >
//       <Show when={merged.label}>
//         <div
//           class={merged.labelClass ?? 'knob-label'}
//           style={getStyleString(getLabelStyle())}
//         >
//           {merged.label}
//         </div>
//       </Show>
//       <div ref={containerRef!} /> {/* Container for the knob-element */}
//     </div>
//   );
// };

// export default KnobComponent;
