// packages/audio-components/src/frameworks/react/types.ts
// src/frameworks/react/types.ts
import { ComponentProps } from 'react';
import { KnobChangeEventDetail } from '../../elements/primitives/KnobElement';

// Extend React JSX namespace for direct knob-element usage
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'knob-element': ComponentProps<'div'> & {
        // Value configuration
        'min-value'?: string | number;
        'max-value'?: string | number;
        'default-value'?: string | number;
        value?: string | number;

        // Snapping configuration
        'snap-increment'?: string | number;
        'allowed-values'?: string; // JSON string
        'snap-thresholds'?: string; // JSON string

        // Rotation configuration
        'min-rotation'?: string | number;
        'max-rotation'?: string | number;

        // Visual configuration
        width?: string | number;
        height?: string | number;
        color?: string;
        'border-style'?: 'currentState' | 'fullCircle';
        curve?: string | number;

        // State
        disabled?: boolean;

        // Event handlers (React style)
        onknobchange?: (event: CustomEvent<KnobChangeEventDetail>) => void;
        'onknob-change'?: (event: CustomEvent<KnobChangeEventDetail>) => void;

        // Standard HTML attributes
        ref?: React.Ref<HTMLElement>;
        className?: string;
        style?: React.CSSProperties;
        title?: string;
        id?: string;
        tabIndex?: number;
        role?: string;
        'aria-label'?: string;
        'aria-valuemin'?: number;
        'aria-valuemax'?: number;
        'aria-valuenow'?: number;
        'aria-orientation'?: 'horizontal' | 'vertical';
        'data-testid'?: string;
      };
    }
  }
}

// Export empty object to make this a module
export {};

// packages/audio-components/src/frameworks/solidjs/types.ts
// src/frameworks/solidjs/types.ts
import { JSX } from 'solid-js';

import { KnobChangeEventDetail } from '../../elements/primitives/KnobElement';

// Extend SolidJS JSX namespace for direct knob-element usage
declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'knob-element': {
        // Value configuration
        'min-value'?: string | number;
        'max-value'?: string | number;
        'default-value'?: string | number;
        value?: string | number;

        // Snapping configuration
        'snap-increment'?: string | number;
        'allowed-values'?: string; // JSON string
        'snap-thresholds'?: string; // JSON string

        // Rotation configuration
        'min-rotation'?: string | number;
        'max-rotation'?: string | number;

        // Visual configuration
        width?: string | number;
        height?: string | number;
        color?: string;
        'border-style'?: 'currentState' | 'fullCircle';
        curve?: string | number;

        // State
        disabled?: boolean | '';

        // Event handlers (SolidJS style)
        'onknob-change'?: JSX.EventHandlerUnion<
          HTMLElement,
          CustomEvent<KnobChangeEventDetail>
        >;
        'on:knob-change'?: JSX.EventHandlerUnion<
          HTMLElement,
          CustomEvent<KnobChangeEventDetail>
        >;

        // Standard HTML attributes
        ref?: HTMLElement | ((el: HTMLElement) => void);
        class?: string;
        classList?: { [k: string]: boolean | undefined };
        style?: JSX.CSSProperties | string;
        id?: string;

        // ARIA attributes for accessibility
        'aria-label'?: string;
        'aria-valuemin'?: string | number;
        'aria-valuemax'?: string | number;
        'aria-valuenow'?: string | number;
        'aria-valuetext'?: string;
        role?: string;
      };
    }
  }
}

// Re-export types from core for convenience
export type {
  KnobConfig,
  KnobChangeEventDetail,
} from '../../elements/primitives/KnobElement';

export type { KnobComponentProps } from './primitives/knob/KnobComponent';
